__all__ = ["USER_DATA_ARGUMENT_NAME", "KNOWLEDGE_ASSESMENT_DATA_ARGUMENT_NAME", "SCHOOL_GRADE_DATA_ARGUMENT_NAME",
           "QUESTION_DATA_ARGUMENT_NAME"]
USER_DATA_ARGUMENT_NAME = "user_data"
KNOWLEDGE_ASSESMENT_DATA_ARGUMENT_NAME = "test_result_data"
SCHOOL_GRADE_DATA_ARGUMENT_NAME = "school_grade_data"
QUESTION_DATA_ARGUMENT_NAME = "question_data"